# Generated by Django 3.1.3 on 2020-12-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
            ],
        ),
    ]
