# Generated by Django 3.1.3 on 2020-12-04 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201204_1944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_detail',
            new_name='User',
        ),
    ]
